ads/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "ads"

classInfoSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView
#from classroom.views import index


urlpatterns = [
  path('admin/', admin.site.urls),
  path('',include('classroom.urls')),
  path('login/', LoginView,{'template_name': 'registration/login.html'})
 
    #path('',index,name ="index"),
    #path('class/',include("classroom.urls")), 

] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

classroom/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
app_name = "classroom"


urlpatterns = [
    path('', views.classpick,name="home"),
    path('about/<str:pk_test>/',views.about,name="about"),
    path('about/<str:pk_test>/schedule',views.schedule,name="schedule"),
    path('about/<str:pk_test>/information',views.information,name="information"),
]

ads/models.py
from django.db import models

# Create your models here.

class Ads(models.Model):
    ads_name = models.CharField(max_length = 50,unique=True,verbose_name="Ads Name")
    dep_name =models.ManyToManyField("department.Department",verbose_name="Department Name")
    image_ads = models.ImageField(upload_to='image',blank=True,verbose_name="Image of Ads")
    def __str__(self):
       return self.ads_name

classroom/models.py
from django.db import models


# Create your models here.

class Classroom(models.Model):
    department_name = models.ManyToManyField("department.Department",verbose_name="Department Name")
    lecture_name = models.ManyToManyField("lecture.Lecture",verbose_name= "lecture name")
    classroom_name = models.CharField(max_length = 50,unique=True,verbose_name="Classroom Name")
   
    
    def __str__(self):
       return self.classroom_name

# https://www.youtube.com/watch?v=PD3YnPSHC-c&list=PL-51WBLyFTg2vW-_6XBoUpE7vpmoR3ztO&index=7



'''

# Create your models here. Wassup
class Classroom(models.Model):
    name = models.CharField(max_length=15, null=False, default="001")
    type = models.CharField(max_length=50, null=False, default="Class")
    capacity = models.IntegerField(default=0)
    exam_capacity = models.IntegerField(default=0)
    sync_token = models.CharField(max_length=256, null=True, default=None)

    def __str__(self):
        return self.name


class Reservation(models.Model):
    by = models.ForeignKey(get_user_model(), null=False, default=1, on_delete=models.SET_DEFAULT)
    res_class = models.ManyToManyField(Classroom)
    description = models.TextField(max_length=350, default="")
    student_total = models.IntegerField(default=0)
    instructor = models.CharField(max_length=1024,null=True)
    proctor_count = models.IntegerField(null=True)
    res_date_start = models.DateTimeField(null=True)
    res_date_end = models.DateTimeField(null=True)
    id_list = ArrayField(models.CharField(max_length=256, null=True, default=None), null=True, default=None)

'''

department/models.py
from django.db import models

# Create your models here.


class Department(models.Model):
    d_name = models.CharField(max_length = 50,unique=True,verbose_name="Department Name")
    def  __str__(self):
       return self.d_name
       

events/models.py
from django.db import models

# Create your models here.
class Events(models.Model):
    event_name = models.CharField(max_length = 50,unique=True,verbose_name="Event Name")
    dept_name =models.ManyToManyField("department.Department",verbose_name="Department Name")
    image_events = models.ImageField(upload_to='image',blank=True,verbose_name="Picture of Event")
    def __str__(self):
       return self.event_name

lecture/models.py
from django.db import models

# Create your models here.
class Lecture(models.Model):
        l_name = models.CharField(max_length = 50,unique=True,verbose_name="Course Name")
        l_date = models.DateTimeField(auto_now_add= False,verbose_name="Course Start Date")
        l_date_end = models.DateTimeField(auto_now_add= False,verbose_name="Course Finish Date")
        ta_name = models.ManyToManyField("ta.TA",verbose_name="Instructor Name")
        
        def __str__(self):
          return self.l_name

student/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    department_name = models.ManyToManyField("department.Department",verbose_name="Department Name")
    lecture_name = models.ManyToManyField("lecture.Lecture",verbose_name="lecture_name")
    studentfullname = models.CharField(max_length = 50)
    studentbdate = models.DateTimeField(auto_now_add= False)
    def __str__(self):
       return self.studentfullname

ta/models.py
from django.db import models

# Create your models here.
# Create your models here.
class TA(models.Model):
        ta_name = models.CharField(max_length = 50,unique=True,verbose_name="Instructor Name ")
        ta_bdate = models.DateTimeField(auto_now_add= False,verbose_name="Instructor Birthday ")
        image_events = models.ImageField(upload_to='image',blank=True,verbose_name="Picture of Instructor ")
    
     
        def __str__(self):
          return self.ta_name

ads/views.py
from django.shortcuts import render

# Create your views here.

classroom/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from lecture.models import *
from department.models import *
from ads.models import *
from events.models import *
from student.models import *
from datetime import datetime
from django.utils import timezone
from ta.models import *
import pytz



def classpick(request):
    classes = Classroom.objects.all()
    
    context = {
        'class':classes,
        
    }
    return render(request, 'index.html',context)

def about(request,pk_test):
    classes = Classroom.objects.get(classroom_name=pk_test)
    department = Department.objects.all()
    ads= Ads.objects.all()
    events= Events.objects.all()
    student=Student.objects.all()
    lectures = Lecture.objects.all()
    mydate = datetime.today()
    context = {'classes':classes,'department':department,'ads':ads,'student':student,'lecture':lectures,'mydate':mydate,'events':events}
    return render(request,'about.html',context)

def schedule(request,pk_test):
    student=Student.objects.all()
    lectures = Lecture.objects.all()
    mydate = datetime.today()
    classes = Classroom.objects.get(classroom_name=pk_test)
    department = Department.objects.all()
    ads= Ads.objects.all()
    context = {'classes':classes,'department':department,'ads':ads,'student':student,'lecture':lectures,'mydate':mydate}
    return render(request,'schedule.html',context)
    
def information(request,pk_test):
    ta = TA.objects.all()
    classes = Classroom.objects.get(classroom_name=pk_test)
    department = Department.objects.all()
    ads= Ads.objects.all()
    events= Events.objects.all()
    student=Student.objects.all()
    lectures = Lecture.objects.all()
    mydate = datetime.today()
    context = {'classes':classes,'department':department,'ads':ads,'student':student,'lecture':lectures,'mydate':mydate,'events':events,'ta':ta}
    return render(request,'information.html',context)

department/views.py
from django.shortcuts import render

# Create your views here.

events/views.py
from django.shortcuts import render

# Create your views here.

lecture/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from lecture.models import *
from department.models import *
from ads.models import *
from student.models import *
from datetime import datetime
import pytz

schedule/views.py
from django.shortcuts import render

# Create your views here.

student/views.py
from django.shortcuts import render

# Create your views here.

ta/views.py
from django.shortcuts import render

# Create your views here.

templates/idle.html
<link rel="stylesheet" href="styles.css">

templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  
  

    <style>
      body {
        background-image: url('https://www.mef.edu.tr/images/logo_tr_color.png');
      background-repeat: no-repeat;
      background-attachment: fixed;
     background-size: cover;

  text-align: center;
}





.card {
  
  border-radius: 2px;
  display: inline-block;
  height: 150px;
  margin: 1rem;
  position: relative;
  width: 200px;
}


    </style>

<style>
  .bar {
  background: blue;
  width: 100px;
  height: 100px;
  float: left;
  margin: 1em;
}
</style>
  <style>

   
#bg img {
  position: absolute; 
  top: 0; 
  left: 0; 
  right: 0; 
  bottom: 0; 
  margin: auto; 
  min-width: 50%;
  min-height: 50%;
}
    
    </style>
<head>
     <link rel="stylesheet" href="main.css">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classes</title>
</head>

<body style="background-color: rgba(50, 115, 220, 0.3)">
    

    {% for i in class %}



<div class="card" style="float: left; margin: 1rem; background-color: #86f0f0;">
  
    <div class="container">
    <div class="card-body" style="display: table-cell">
      <h3 class="card-title">Class No: {{i.classroom_name}}</h3>
      <a href="{% url 'classroom:about' i.classroom_name %}" class="btn btn-dark">Login</a></p>
    </div>
    </div>
  
  
</div>




    
    {% endfor %}


</body>
</html>

templates/information.html
{%load static%}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

    
    <style>

   
body {
	background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
	background-size: 400% 400%;
	animation: gradient 15s ease infinite;
}

@keyframes gradient {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}
    
            
            </style>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="animista.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&family=Cinzel&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>

 <h2 style="text-align: center;" class="tracking-in-expand">Time: {{mydate|date}} {{mydate|time:"h:i A"}}</h2>
 <br>


 {% for i in classes.lecture_name.all %}
 {% for p in i.ta_name.all %}
 {% for k in classes.lecture_name.all %}
 {%if mydate|time:"H" >= k.l_date|time:"H" and mydate|time:"H" <= k.l_date_end|time:"H" %}
 {%if k.l_date|date:"l" == mydate|date:"l" %}
 <!--
 <h1>Şuan ki ders: {{i}}</h1>
 <h1> Şuan ki dersin hocası: {{p}} </h1>
 <h1>  Şuan ki dersin hocasının doğum günü: {{p.ta_bdate}} </h1> -->
 
 <div class="card" style="width:400px; margin: 0 auto; float: none; margin-bottom: 10px;">
  <img class="card-img-top" src="/image/{{p.image_events}}" alt="Card image" style="width:100%">
  <div class="card-body" style="font-family: 'Cinzel', serif;">
     {%if mydate|date ==  p.ta_bdate|date %}
     <h2 class="card-title" style="font-family: 'Chelsea Market', cursive; padding-bottom: 10px;
     text-align: center"> Happy Birthday {{p}} !</h2>
     {%endif%}
    <h4 class="card-title" style="padding-bottom: 10px;
            text-align: center;
    
    bottom: 0px"> {{p}}</h4>
    <h6 class="card-title" style="padding-bottom: 10px;
  
    text-align: center;
    
    bottom: 0px">Lecture Name: {{i}}</h6>
    <h6 style="padding-bottom: 10px;
  
    text-align: center;
    
    bottom: 0px">Lecture Starts at: {{i.l_date|time:"G:i"}}</h6 >

     <h6 style="padding-bottom: 10px;
     padding-top: 1%;
     text-align: center;
     
     bottom: 0px">Lecture Finishes at: {{i.l_date_end|time:"G:i"}}</h6 >
    
  
    
  </div>
</div>
{%endif%}
{%endif%}
{% endfor %}
 {% endfor %}
 {% endfor %}
 
     <!-- Hocanın Sınıfını Getirir
    {% for k in classes.lecture_name.all %}
  
    {%if mydate|time:"H" >= k.l_date|time:"H" and mydate|time:"H" <= k.l_date_end|time:"H" %}
  
    
    {%if k.l_date|date:"l" == mydate|date:"l" %}
    {% for i in classes.lecture.name.all %}
    
    {% for j in  i.classroom_name.all %}
 -->

     <!--<h1>Hocanın Sınıfı: {{j}}</h1>-->
     
   
   

    <!--İçerisinde Bulunduğumuz Sınıf-->
    
    <!-- <h1>Şuan ki sınıf : {{classes}}</h1> -->
    <!--
     
    {%if j == classes %}
    <div class="card" style="width:400px; margin: 0 auto; float: none; margin-bottom: 10px;">
      <img class="card-img-top" src="/image/{{i.image_events}}" alt="Card image" style="width:100%">
      <div class="card-body" style="font-family: 'Cinzel', serif;">
         {%if mydate|date ==  i.ta_bdate|date %}
         <h2 class="card-title" style="font-family: 'Chelsea Market', cursive; padding-bottom: 10px;
         text-align: center"> Happy Birthday {{i}} !</h2>
         {%endif%}
        <h4 class="card-title" style="padding-bottom: 10px;
                text-align: center;
        
        bottom: 0px"> {{i}}</h4>
        <h6 class="card-title" style="padding-bottom: 10px;
      
        text-align: center;
        
        bottom: 0px">Lecture Name: {{k}}</h6>
        <h6 style="padding-bottom: 10px;
      
        text-align: center;
        
        bottom: 0px">Lecture Starts at: {{k.l_date|time:"G:i"}}</h6 >
 
         <h6 style="padding-bottom: 10px;
         padding-top: 1%;
         text-align: center;
         
         bottom: 0px">Lecture Finishes at: {{k.l_date_end|time:"G:i"}}</h6 >
        
      
        
      </div>
    </div>
    -->
    <!--
    {%endif%}
    
    {% endfor %}
    {% endfor %}
    {%endif%}
    {%endif%}
    {% endfor %}


    {% for i in classes.lecture_name.all %}
    {% for l in class %}
    {% for j in ta %}
    {% for k in j.classroom_name.all %}
    -->
    <!--- <h1>Lecture name: {{i}}</h1>
     <h1>lecture start time:  {{i.l_date|time:"H"}} </h1>
     <h1>lecture end time:  {{i.l_date_end|time:"H"}} </h1>
     <h3> current time:  {{mydate|time:"H"}} </h3>
  -->
  <!--
    <h1>
       Öğretmenin Sınıfı:  {{k}}
    </h1>

    <h1>
       Şuan ki ders:  {{l.classroom_name}}


    </h1>
    
    {%if mydate|time:"H" >= i.l_date|time:"H" and mydate|time:"H" <= i.l_date_end|time:"H" %}
    {%if i.l_date|date:"l" == mydate|date:"l" %}

   
    {%if j.lecture_name == i.lecture_name and k == i.classroom_name %}
         <h1>Lecturer Name: {{j.ta_name}}</h1>
    
       
      <h1 class="text-light" style="padding-bottom: 10px;
      padding-top: 1%;
      text-align: center;
      
      bottom: 0px">Current Lecture: {{i}}</h1 >
      -->
 <!--  <div class="container">
    <h2>Card Image</h2>
    <p>Image at the top (card-img-top):</p>
    <div class="card" style="width:400px">
      <img class="card-img-top" src="img_avatar1.png" alt="Card image" style="width:100%">
      <div class="card-body">
        <h4 class="card-title">John Doe</h4>
        <p class="card-text">Some example text some example text. John Doe is an architect and engineer</p>
        <a href="#" class="btn btn-primary">See Profile</a>
      </div>
    </div>
    -->

      
        
     <!--- <h5>{{i.l_date}}</h5>
      <h5>{{i.l_date_end}}</h5>
     <h5>{{i.l_date}}</h5>
     -->
<!--
     {% endif %}
     {% endif %}
    {% endif %}
    {% endfor %}
    {% endfor %}
    {% endfor %}
    {% endfor %}
-->
  
</body>
</html>